### ISSUE TITLE
No such file or directory on first run

### ISSUE THREAD

**Issue by kennethgillen** [ome/ansible-role-jekyll-build#3]
First run of this role:

```
RUNNING HANDLER [openmicroscopy.jekyll-build : update bundle] ****************************************************************
fatal: [infra-testpr.openmicroscopy.org]: FAILED! => {"changed": false, "cmd": "bundle install", "failed": true, "msg": "[Errn
o 2] No such file or directory", "rc": 2}

```

but a re-run, with `-v` to assist with debugging, and the role succeeded.

So there may be a sequence bug with some part of the play relying on something which has not yet been created, which _is_ created later on.

**Comment by sbesson** [comment]
@kennethgillen thanks, it looks like this error is not raised in the molecule tests for this role. Do you have a commit/branch containing the playbook allowing to reproduce the failure?

**Comment by kennethgillen** [comment]
@sbesson - no worries. 


The following commit of the PR open for server `www-dev` 
: https://github.com/openmicroscopy/infrastructure/pull/281/commits/4899be0d755b8106683c9f78c79caa8f91a96838 ([some server config vars are private](https://github.com/openmicroscopy/management_tools/pull/474), but accessible to the OME team at least, and not relevant to replication of this issue for anyone following along.) 

Initially this was run without `jekyll_build_force_rebuild: True` - and therefore with the default `jekyll_build_force_rebuild: False`. 

That means Jekyll didn't try to run the build, and so the playbook could continue past this point on the second run.

After setting this to `True` - the playbook continually fails until dependencies are manually installed. 

(The issue is that the deps for these packages require Ruby > 2.0.0 which is what we get with CentOS 7)

It seems the inclusion of (at least) 
  * jekyll-feed
  * html-proofer 

Perhaps Ruby tries to install them at run-time and hence the initial install doesn't bail when it's not trying to run the Jekyll build at playbook-time.

**Comment by manics** [comment]
When you figure this out it might be worth adding `Gemfile.lock` to https://github.com/openmicroscopy/www.openmicroscopy.org.
- http://bundler.io/deploying.html

It might also be worth looking at `bundle install --deployment`, to prevent gems being installed globally
- http://bundler.io/deploying.html

**Comment by kennethgillen** [comment]
After manually installing my gem dependencies on a fresh server, in advance of running this role, we still hit this error.
