### ISSUE TITLE
Jekyll installation is currently broken

### ISSUE THREAD

**Issue by manics** [ome/ansible-role-jekyll-build#8]
Role version: `1.2.0`
`molecule test`:
```
...

TASK [ansible-role-jekyll-build : jekyll | install jekyll] *********************
fatal: [jekyll-build-dual-config]: FAILED! => {"changed": false, "cmd": "/usr/bin/gem install --version 3.4.3 --no-user-install --no-document jekyll", "failed": true, "msg": "ERROR:  Error installing jekyll:\n\tpublic_suffix requires Ruby version >= 2.1.", "rc": 1, "stderr": "ERROR:  Error installing jekyll:\n\tpublic_suffix requires Ruby version >= 2.1.\n", "stderr_lines": ["ERROR:  Error installing jekyll:", "\tpublic_suffix requires Ruby version >= 2.1."], "stdout": "", "stdout_lines": []}
fatal: [jekyll-build-default]: FAILED! => {"changed": false, "cmd": "/usr/bin/gem install --version 3.4.3 --no-user-install --no-document jekyll", "failed": true, "msg": "ERROR:  Error installing jekyll:\n\tpublic_suffix requires Ruby version >= 2.1.", "rc": 1, "stderr": "ERROR:  Error installing jekyll:\n\tpublic_suffix requires Ruby version >= 2.1.\n", "stderr_lines": ["ERROR:  Error installing jekyll:", "\tpublic_suffix requires Ruby version >= 2.1."], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
jekyll-build-default       : ok=6    changed=5    unreachable=0    failed=1
jekyll-build-dual-config   : ok=6    changed=5    unreachable=0    failed=1
```

**Comment by sbesson** [comment]
Thanks for raising this. Trying to look into the impact on our test coverage: https://travis-ci.org/openmicroscopy/ansible-role-jekyll-build/builds/254248735 built a month ago passed while https://travis-ci.org/sbesson/ansible-role-jekyll-build/builds/268330501 pushed today from the same SHA1 failed so something upstream must be stricter.

Given the importance of this role for the various Website deployments (IDR, OME), I would count this as high-priority /cc @kennethgillen. The two options I can think of are:

- lowering the version of Jekyll to be 2.0 compatible although it's unclear how this will impact Jekyll plugins used for the websites
- install a more recent version of Ruby either via a repo or via `rvm`. While looking into this role, I had considered https://github.com/rvm/rvm1-ansible as an upstream dependency but this is untested on CentOS7.

**Comment by manics** [comment]
Given my past experiences with rvm I'd prefer it if we could avoid it (may require a full development/compilation environment, a lot of dependencies, and may still break if you're not careful).

**Comment by manics** [comment]
An alternative might be the [Ansible bundler module](http://docs.ansible.com/ansible/latest/bundler_module.html) that takes a `Gemfile` with a full list of dependencies, similar to the output of python `pip freeze`. I'd expect that assuming the download servers were online this would guarantee the the installation, at the expense of us updating the Gemfile versions when required to fix bugs or secvulns.

**Comment by manics** [comment]
I've create a `Gemfile.lock` from the jekyll installation on an existing working IDR server:
`Gemfile`:
```
gem 'jekyll'
```
`bundler lock` creates `Gemfile.lock`:
```
GEM
  specs:
    addressable (2.5.1)
      public_suffix (~> 2.0, >= 2.0.2)
    colorator (1.1.0)
    ffi (1.9.18)
    forwardable-extended (2.6.0)
    jekyll (3.4.3)
      addressable (~> 2.4)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-sass-converter (1.5.0)
      sass (~> 3.4)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.14.0)
    liquid (3.0.6)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    public_suffix (2.0.5)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.5.1)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll

BUNDLED WITH
   1.15.3
```
